import "./globals.css";
import { Abhaya_Libre, Great_Vibes } from "next/font/google";

const inter = Abhaya_Libre({
  subsets: ["sinhala"],
  weight: "400",
});

const adelia = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-adelia",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${adelia.variable}`}>
        {children}
      </body>
    </html>
  );
}
